@echo off
echo Setup ReportGenerator environment variables.

set "SWP_REPORTGENERATOR_VERSION_MAJOR=2"
set "SWP_REPORTGENERATOR_VERSION_MINOR=1"
set "SWP_REPORTGENERATOR_VERSION_SUBMINOR=4"

set "SWP_REPORTGENERATOR_VERSION=%SWP_REPORTGENERATOR_VERSION_MAJOR%.%SWP_REPORTGENERATOR_VERSION_MINOR%.%SWP_REPORTGENERATOR_VERSION_SUBMINOR%"

set "SWP_REPORTGENERATOR_ROOT=%SWP_TOOLS_ROOT%/ReportGenerator-%SWP_REPORTGENERATOR_VERSION%"

set "SWP_REPORTGENERATOR_CMD_EXE=%SWP_REPORTGENERATOR_ROOT%/bin/ReportGenerator.exe"


REM output all ReportGenerator relevant environmental variables:
set SWP_REPORTGENERATOR