@echo off


echo Setup ParseArguments environment variables.

set "SWP_PARSEARGUMENTS_VERSION_MAJOR=1"
set "SWP_PARSEARGUMENTS_VERSION_MINOR=0"
set "SWP_PARSEARGUMENTS_VERSION_SUBMINOR=0"

set "SWP_PARSEARGUMENTS_VERSION=%SWP_PARSEARGUMENTS_VERSION_MAJOR%.%SWP_PARSEARGUMENTS_VERSION_MINOR%.%SWP_PARSEARGUMENTS_VERSION_SUBMINOR%"

set "SWP_PARSEARGUMENTS_ROOT=%SWP_TOOLS_ROOT%/ParseArguments-%SWP_PARSEARGUMENTS_VERSION%/"

set "SWP_PARSEARGUMENTS_BAT=%SWP_PARSEARGUMENTS_ROOT%/DOS/ParseOptions.bat"
set "SWP_PARSEARGUMENTS_GUI_BAT=%SWP_PARSEARGUMENTS_ROOT%/DOS/ParseOptionsGUI.bat"

REM output all ParseArguments relevant environmental variables:
set SWP_PARSEARGUMENTS

