@echo off

echo Setup OpenCover environment variables.

set "SWP_OPENCOVER_VERSION_MAJOR=4"
set "SWP_OPENCOVER_VERSION_MINOR=5"
set "SWP_OPENCOVER_VERSION_SUBMINOR=3522"

set "SWP_OPENCOVER_VERSION=%SWP_OPENCOVER_VERSION_MAJOR%.%SWP_OPENCOVER_VERSION_MINOR%.%SWP_OPENCOVER_VERSION_SUBMINOR%"

set "SWP_OPENCOVER_ROOT=%SWP_TOOLS_ROOT%/OpenCover-%SWP_OPENCOVER_VERSION%"

set "SWP_OPENCOVER_CMD_EXE=%SWP_OPENCOVER_ROOT%/OpenCover.Console.exe"


REM output all OpenCover relevant environmental variables:
set SWP_OPENCOVER

