using System;
using GraphFramework.Interfaces;

namespace GraphFramework
{
    public class Attribute : IAttribute
    {
        //  TO EDIT --> code is generated by resharper to match the interface

        public object Value { get; set; }
        public Type Type { get; private set; }
        public string Name { get; set; }
    }
}