using System;
using System.Collections.Generic;
using GraphFramework.Interfaces;

namespace GraphFramework
{
    public abstract class GraphElement : IGraphElement
    {
        //  TO EDIT --> code is generated by resharper to match the interface

        public IEnumerable<IAttribute> Attributes { get; private set; }
        public void AddAttribute(IAttribute attribute)
        {
            throw new NotImplementedException();
        }

        public void RemoveAttribute(string name)
        {
            throw new NotImplementedException();
        }

        public void RemoveAttribute(IAttribute attribute)
        {
            throw new NotImplementedException();
        }
    }
}